-- SQLite
CREATE TABLE Client(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Surname TEXT NOT NULL,
  Names TEXT NOT NULL,
  Email TEXT,
  IsActive INTEGER
);

CREATE TABLE Phone(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Type TEXT NOT NULL,
  Number TEXT NOT NULL,
  ClientId INTEGER,
  FOREIGN KEY(ClientId) REFERENCES Client(Id)
);

CREATE TABLE Address(
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Type TEXT NOT NULL,
  Line1 TEXT NOT NULL,
  Line2 TEXT NOT NULL,
  City TEXT NOT NULL,
  Country TEXT NOT NULL,
  Code TEXT NOT NULL,
  ClientId INTEGER,
  FOREIGN KEY(ClientId) REFERENCES Client(Id)
);